name: Continuous Integration
on: push
jobs:
  unit-tests:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        node-version:
          - 22.x
    steps:
      - uses: actions/checkout@v4
      - name: 'Install node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v2-beta
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Run lint
        run: |
          npm install
          npm run lint && npm ls
          jq . test_cases/*.json > /dev/null
