name: Continuous Integration
on: push
jobs:
  unit-tests:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
        node-version:
          - 10.x
          - 12.x
    steps:
      - uses: actions/checkout@v2
      - name: 'Install node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v2-beta
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Run lint
        run: |
          npm install
          npm run lint && npm ls
